GameShow/GameShow/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GameShow.Models
{
    public class Genre
    {
        public Genre()
        {
            Games = new List<Game>();
        }

        [Key]
        public int IDGenre { get; set; }

        [Required]
        [StringLength(32, ErrorMessage = "Gateunek gry ma maksymalnie 32 znaki.")]
        [DisplayName("Gantunek gry")]
        public string GenreName { get; set; }

        [ForeignKey("IDGame")]
        public virtual ICollection<Game> Games { get; set; }

        [MaxLength(8)]
        [Timestamp]
        public byte[] Stamp { get; set; }

        public override string ToString()
        {
            return GenreName;
        }

        public override bool Equals(object obj)
        {
            Genre genre = obj as Genre;
            if (genre == null)
            {
                return false;
            }
            return GenreName == genre.GenreName &&
                IDGenre == genre.IDGenre;
        }
    }
}

GameShow/GameShow/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GameShow.Models;
using System.Configuration;
using PagedList;

namespace GameShow.Controllers
{
    public class GenresController : Controller
    {
        private Storage storage = new Storage();
        public virtual Storage Storage
        {
            get
            {
                return storage;
            }
            set
            {
                storage = value;
            }
        }
        private int groupsPerPage = Int32.Parse(ConfigurationManager.AppSettings["GenresPerPage"]);

        // GET: PagedGroups
        public ActionResult Index(int? page, string errorMessage)
        {
            try
            {
                int currentPage = (page ?? 1);

                var genresList = storage.GetGenres();

                return View(new GenresDTO() { ErrorMessage = errorMessage, PagedGenres = genresList.ToPagedList(currentPage == 0 ? 1 : currentPage, groupsPerPage) });
            }
            catch (Exception ex)
            {
                return View(new GenresDTO() { ErrorMessage = ex.Message, PagedGenres = storage.GetGenres().ToPagedList(1, groupsPerPage) });
            }
        }
     

        // GET: PagedGroups/Details/5
        public ActionResult GenreForms(GenresDTO genresList, string request)
        {
            try
            {
                var genre = genresList.SelectedGenre;

                switch (request)
                {
                    case ("Create"):
                        storage.CreateGenre(genre);
                        break;
                    case ("Edit"):
                        storage.UpdateGenre(genre);
                        break;
                    case ("Delete"):
                        storage.DeleteGenre(genre);
                        break;
                    default:
                        throw new Exception("Akcja przycisku niezdefiniowana!");
                }
                return RedirectToAction("Index", new { page = genresList.Page });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", new { page = 1, errorMessage = ex.Message });
            }
        }
    }
}

GameShow/GameShow/Views/Genres/Create.cshtml
@model GameShow.Models.Genre

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GenreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenreName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameShow/GameShow/Views/Genres/Delete.cshtml
@model GameShow.Models.Genre

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenreName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stamp)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GameShow/GameShow/Views/Genres/Details.cshtml
@model GameShow.Models.Genre

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenreName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stamp)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDGenre }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GameShow/GameShow/Views/Genres/Edit.cshtml
@model GameShow.Models.Genre

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDGenre)

        <div class="form-group">
            @Html.LabelFor(model => model.GenreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GenreName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameShow/GameShow/Views/Genres/Index.cshtml
@model GameShow.Models.GenresDTO
@using PagedList.Mvc;


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />
<h3>Lista Stylów Gry</h3>

@{
    if (!String.IsNullOrEmpty(Model.ErrorMessage))
    {
        <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <strong>Error!</strong> @Model.ErrorMessage
        </div>
    }
}

<table class="table table-bordered table-hover col-md-12">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SelectedGenre.IDGenre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectedGenre.GenreName)
        </th>

    </tr>

    @foreach (var item in Model.PagedGenres)
    {
        <tr id="@("genre" + item.IDGenre)" onclick="editGenre(@item.IDGenre)">

            <td class="genre-id">
                @Html.DisplayFor(modelItem => item.IDGenre)
            </td>
            <td class="genre-name">
                @Html.DisplayFor(modelItem => item.GenreName)
            </td>
            @Html.HiddenFor(modelItem => item.Stamp, new { @class = "genre-stamp" })


        </tr>
    }

</table>

<br />
Page @(Model.PagedGenres.PageCount < Model.PagedGenres.PageNumber ? 0 : Model.PagedGenres.PageNumber) of @Model.PagedGenres.PageCount

@Html.PagedListPager(Model.PagedGenres, page => Url.Action("Index",
new { page }))


@using (Html.BeginForm("GenreForms", "Genres"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edycja</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedGenre.GenreName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.SelectedGenre.GenreName, new { htmlAttributes = new { @class = "form-control kontrolka-dolna", @id = "form-genre-name" } })
                @Html.ValidationMessageFor(model => model.SelectedGenre.GenreName, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.SelectedGenre.IDGenre, new { @id = "form-genre-id" })
        @Html.HiddenFor(model => model.SelectedGenre.Stamp, new { @id = "form-genre-stamp" })

        <div class="form-group">
            <div class="col-md-8">
                <div class="pull-right">
                    <button type="submit" name="request" id="creategenre" value="Create" class="btn btn-primary przycisk-dolny">Nowa</button>
                    <button type="submit" name="request" id="editgenre" value="Edit" class="btn btn-primary przycisk-dolny" disabled>Zapisz</button>
                    <button type="submit" name="request" id="deletegenre" value="Delete" class="btn btn-primary przycisk-dolny" disabled>Usuń</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function editGenre(rowId) {
            var prnt = $("#genre" + rowId);
            $("#form-genre-name").val(prnt.find(".genre-name").text().trim());
            $("#form-genre-stamp").val(prnt.find(".genre-stamp").val());
            $("#form-genre-id").val(prnt.find(".genre-id").text().trim());


            document.getElementById("editgenre").disabled = false;
            document.getElementById("deletegenre").disabled = false;
        }
    </script>

}